// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: doubao.proto

package doubaopb

import (
	context "context"
	doubao "github.com/yazl-tech/ai-bot/pkg/dto/doubao"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DoubaoService_ChatCompletions_FullMethodName = "/DoubaoService/ChatCompletions"
)

// DoubaoServiceClient is the client API for DoubaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoubaoServiceClient interface {
	ChatCompletions(ctx context.Context, in *doubao.ChatRequest, opts ...grpc.CallOption) (*doubao.ChatResponse, error)
}

type doubaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoubaoServiceClient(cc grpc.ClientConnInterface) DoubaoServiceClient {
	return &doubaoServiceClient{cc}
}

func (c *doubaoServiceClient) ChatCompletions(ctx context.Context, in *doubao.ChatRequest, opts ...grpc.CallOption) (*doubao.ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(doubao.ChatResponse)
	err := c.cc.Invoke(ctx, DoubaoService_ChatCompletions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoubaoServiceServer is the server API for DoubaoService service.
// All implementations must embed UnimplementedDoubaoServiceServer
// for forward compatibility.
type DoubaoServiceServer interface {
	ChatCompletions(context.Context, *doubao.ChatRequest) (*doubao.ChatResponse, error)
	mustEmbedUnimplementedDoubaoServiceServer()
}

// UnimplementedDoubaoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoubaoServiceServer struct{}

func (UnimplementedDoubaoServiceServer) ChatCompletions(context.Context, *doubao.ChatRequest) (*doubao.ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatCompletions not implemented")
}
func (UnimplementedDoubaoServiceServer) mustEmbedUnimplementedDoubaoServiceServer() {}
func (UnimplementedDoubaoServiceServer) testEmbeddedByValue()                       {}

// UnsafeDoubaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoubaoServiceServer will
// result in compilation errors.
type UnsafeDoubaoServiceServer interface {
	mustEmbedUnimplementedDoubaoServiceServer()
}

func RegisterDoubaoServiceServer(s grpc.ServiceRegistrar, srv DoubaoServiceServer) {
	// If the following call pancis, it indicates UnimplementedDoubaoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoubaoService_ServiceDesc, srv)
}

func _DoubaoService_ChatCompletions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(doubao.ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoubaoServiceServer).ChatCompletions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoubaoService_ChatCompletions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoubaoServiceServer).ChatCompletions(ctx, req.(*doubao.ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoubaoService_ServiceDesc is the grpc.ServiceDesc for DoubaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoubaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DoubaoService",
	HandlerType: (*DoubaoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatCompletions",
			Handler:    _DoubaoService_ChatCompletions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doubao.proto",
}
