// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.23.4
// source: doubao.proto

package doubao

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageParam        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_doubao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doubao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_doubao_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessages() []*MessageParam {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Choice        *Choices               `protobuf:"bytes,2,opt,name=choice,proto3" json:"choice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_doubao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doubao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_doubao_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatResponse) GetChoice() *Choices {
	if x != nil {
		return x.Choice
	}
	return nil
}

type MessageParam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*MessageParam_StringContent
	//	*MessageParam_TypeContent
	Content       isMessageParam_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageParam) Reset() {
	*x = MessageParam{}
	mi := &file_doubao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageParam) ProtoMessage() {}

func (x *MessageParam) ProtoReflect() protoreflect.Message {
	mi := &file_doubao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageParam.ProtoReflect.Descriptor instead.
func (*MessageParam) Descriptor() ([]byte, []int) {
	return file_doubao_proto_rawDescGZIP(), []int{2}
}

func (x *MessageParam) GetContent() isMessageParam_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessageParam) GetStringContent() *StringMessage {
	if x != nil {
		if x, ok := x.Content.(*MessageParam_StringContent); ok {
			return x.StringContent
		}
	}
	return nil
}

func (x *MessageParam) GetTypeContent() *TypeMessage {
	if x != nil {
		if x, ok := x.Content.(*MessageParam_TypeContent); ok {
			return x.TypeContent
		}
	}
	return nil
}

type isMessageParam_Content interface {
	isMessageParam_Content()
}

type MessageParam_StringContent struct {
	StringContent *StringMessage `protobuf:"bytes,1,opt,name=string_content,json=stringContent,proto3,oneof"`
}

type MessageParam_TypeContent struct {
	TypeContent *TypeMessage `protobuf:"bytes,2,opt,name=type_content,json=typeContent,proto3,oneof"`
}

func (*MessageParam_StringContent) isMessageParam_Content() {}

func (*MessageParam_TypeContent) isMessageParam_Content() {}

type StringMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	mi := &file_doubao_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_doubao_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_doubao_proto_rawDescGZIP(), []int{3}
}

func (x *StringMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *StringMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TypeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       *TypeMessage_Content   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeMessage) Reset() {
	*x = TypeMessage{}
	mi := &file_doubao_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeMessage) ProtoMessage() {}

func (x *TypeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_doubao_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeMessage.ProtoReflect.Descriptor instead.
func (*TypeMessage) Descriptor() ([]byte, []int) {
	return file_doubao_proto_rawDescGZIP(), []int{4}
}

func (x *TypeMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TypeMessage) GetContent() *TypeMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type Choices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message       *StringMessage         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Created       int64                  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choices) Reset() {
	*x = Choices{}
	mi := &file_doubao_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choices) ProtoMessage() {}

func (x *Choices) ProtoReflect() protoreflect.Message {
	mi := &file_doubao_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choices.ProtoReflect.Descriptor instead.
func (*Choices) Descriptor() ([]byte, []int) {
	return file_doubao_proto_rawDescGZIP(), []int{5}
}

func (x *Choices) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Choices) GetMessage() *StringMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Choices) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *Choices) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Choices) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type TypeMessage_ImageUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeMessage_ImageUrl) Reset() {
	*x = TypeMessage_ImageUrl{}
	mi := &file_doubao_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeMessage_ImageUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeMessage_ImageUrl) ProtoMessage() {}

func (x *TypeMessage_ImageUrl) ProtoReflect() protoreflect.Message {
	mi := &file_doubao_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeMessage_ImageUrl.ProtoReflect.Descriptor instead.
func (*TypeMessage_ImageUrl) Descriptor() ([]byte, []int) {
	return file_doubao_proto_rawDescGZIP(), []int{4, 0}
}

func (x *TypeMessage_ImageUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type TypeMessage_Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ImageUrl      *TypeMessage_ImageUrl  `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeMessage_Content) Reset() {
	*x = TypeMessage_Content{}
	mi := &file_doubao_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeMessage_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeMessage_Content) ProtoMessage() {}

func (x *TypeMessage_Content) ProtoReflect() protoreflect.Message {
	mi := &file_doubao_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeMessage_Content.ProtoReflect.Descriptor instead.
func (*TypeMessage_Content) Descriptor() ([]byte, []int) {
	return file_doubao_proto_rawDescGZIP(), []int{4, 1}
}

func (x *TypeMessage_Content) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TypeMessage_Content) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TypeMessage_Content) GetImageUrl() *TypeMessage_ImageUrl {
	if x != nil {
		return x.ImageUrl
	}
	return nil
}

var File_doubao_proto protoreflect.FileDescriptor

var file_doubao_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x61, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70,
	0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x40, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x20, 0x0a, 0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x52, 0x06, 0x63, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x12, 0x37, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x0c,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xd6, 0x01, 0x0a, 0x0b, 0x54, 0x79,
	0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x2e, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x1c, 0x0a,
	0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x1a, 0x65, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x32,
	0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x72, 0x6c, 0x22, 0x9e, 0x01, 0x0a, 0x07, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x32, 0x41, 0x0a, 0x0d, 0x44, 0x6f, 0x75, 0x62, 0x61, 0x6f, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0c, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x7a, 0x6c, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x61,
	0x69, 0x2d, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x64, 0x6f, 0x75, 0x62, 0x61, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_doubao_proto_rawDescOnce sync.Once
	file_doubao_proto_rawDescData []byte
)

func file_doubao_proto_rawDescGZIP() []byte {
	file_doubao_proto_rawDescOnce.Do(func() {
		file_doubao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doubao_proto_rawDesc), len(file_doubao_proto_rawDesc)))
	})
	return file_doubao_proto_rawDescData
}

var file_doubao_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_doubao_proto_goTypes = []any{
	(*ChatRequest)(nil),          // 0: ChatRequest
	(*ChatResponse)(nil),         // 1: ChatResponse
	(*MessageParam)(nil),         // 2: MessageParam
	(*StringMessage)(nil),        // 3: StringMessage
	(*TypeMessage)(nil),          // 4: TypeMessage
	(*Choices)(nil),              // 5: Choices
	(*TypeMessage_ImageUrl)(nil), // 6: TypeMessage.ImageUrl
	(*TypeMessage_Content)(nil),  // 7: TypeMessage.Content
}
var file_doubao_proto_depIdxs = []int32{
	2, // 0: ChatRequest.messages:type_name -> MessageParam
	5, // 1: ChatResponse.choice:type_name -> Choices
	3, // 2: MessageParam.string_content:type_name -> StringMessage
	4, // 3: MessageParam.type_content:type_name -> TypeMessage
	7, // 4: TypeMessage.content:type_name -> TypeMessage.Content
	3, // 5: Choices.message:type_name -> StringMessage
	6, // 6: TypeMessage.Content.image_url:type_name -> TypeMessage.ImageUrl
	0, // 7: DoubaoHandler.ChatCompletions:input_type -> ChatRequest
	1, // 8: DoubaoHandler.ChatCompletions:output_type -> ChatResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_doubao_proto_init() }
func file_doubao_proto_init() {
	if File_doubao_proto != nil {
		return
	}
	file_doubao_proto_msgTypes[2].OneofWrappers = []any{
		(*MessageParam_StringContent)(nil),
		(*MessageParam_TypeContent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doubao_proto_rawDesc), len(file_doubao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doubao_proto_goTypes,
		DependencyIndexes: file_doubao_proto_depIdxs,
		MessageInfos:      file_doubao_proto_msgTypes,
	}.Build()
	File_doubao_proto = out.File
	file_doubao_proto_goTypes = nil
	file_doubao_proto_depIdxs = nil
}
