// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: doubao.proto

package doubao

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DoubaoHandler_ChatCompletions_FullMethodName = "/DoubaoHandler/ChatCompletions"
)

// DoubaoHandlerClient is the client API for DoubaoHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoubaoHandlerClient interface {
	ChatCompletions(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
}

type doubaoHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewDoubaoHandlerClient(cc grpc.ClientConnInterface) DoubaoHandlerClient {
	return &doubaoHandlerClient{cc}
}

func (c *doubaoHandlerClient) ChatCompletions(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, DoubaoHandler_ChatCompletions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoubaoHandlerServer is the server API for DoubaoHandler service.
// All implementations must embed UnimplementedDoubaoHandlerServer
// for forward compatibility.
type DoubaoHandlerServer interface {
	ChatCompletions(context.Context, *ChatRequest) (*ChatResponse, error)
	mustEmbedUnimplementedDoubaoHandlerServer()
}

// UnimplementedDoubaoHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoubaoHandlerServer struct{}

func (UnimplementedDoubaoHandlerServer) ChatCompletions(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatCompletions not implemented")
}
func (UnimplementedDoubaoHandlerServer) mustEmbedUnimplementedDoubaoHandlerServer() {}
func (UnimplementedDoubaoHandlerServer) testEmbeddedByValue()                       {}

// UnsafeDoubaoHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoubaoHandlerServer will
// result in compilation errors.
type UnsafeDoubaoHandlerServer interface {
	mustEmbedUnimplementedDoubaoHandlerServer()
}

func RegisterDoubaoHandlerServer(s grpc.ServiceRegistrar, srv DoubaoHandlerServer) {
	// If the following call pancis, it indicates UnimplementedDoubaoHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoubaoHandler_ServiceDesc, srv)
}

func _DoubaoHandler_ChatCompletions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoubaoHandlerServer).ChatCompletions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoubaoHandler_ChatCompletions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoubaoHandlerServer).ChatCompletions(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoubaoHandler_ServiceDesc is the grpc.ServiceDesc for DoubaoHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoubaoHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DoubaoHandler",
	HandlerType: (*DoubaoHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatCompletions",
			Handler:    _DoubaoHandler_ChatCompletions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doubao.proto",
}
